In [1]:
import numpy as np

In [3]:
# get index locations that satisfy a given condition using np.where

In [2]:
# Create an array
import numpy as np
arr_rand = np.array([8, 8, 3, 7, 7, 10, 4, 2, 5, 2, 0])
print("Array: ", arr_rand)

Array:  [ 8  8  3  7  7 10  4  2  5  2  0]


In [6]:
arr_rand[arr_rand >5]

array([ 8,  8,  7,  7, 10])

In [5]:
arr_rand[np.where(arr_rand>5)]

array([ 8,  8,  7,  7, 10])

In [7]:
np.where(arr_rand > 5 ,'G5','L5')

array(['G5', 'G5', 'L5', 'G5', 'G5', 'G5', 'L5', 'L5', 'L5', 'L5', 'L5'],
      dtype='<U2')

In [7]:
arr_rand[np.where(arr_rand > 5)]

array([ 8,  8,  7,  7, 10])

In [3]:
# Positions where value > 5
index_gt5 = np.where(arr_rand > 5)
print("Positions where value > 5: ", index_gt5)
arr_rand[index_gt5]

Positions where value > 5:  (array([0, 1, 3, 4, 5], dtype=int64),)


array([ 8,  8,  7,  7, 10])

In [8]:
# extract them using the array’s take method.

# Take items at given index
arr_rand.take([1,3])

array([8, 7])

In [10]:
# If value > 5, then yield 'gt5' else 'le5'

arr_rand = np.array([8, 18, 33, 7, 77, 80, 10, 4, 12, 53, 2, 0, 20,30,40])
print("Array: ", arr_rand)


Array:  [ 8 18 33  7 77 80 10  4 12 53  2  0 20 30 40]


In [ ]:
np.where((arr_rand <10), 'A',  
         np.where(arr_rand <30, 'B', 
                  np.where(arr_rand <50, 'C','D')))

array(['B', 'A', 'A', 'B', 'D', 'D', 'B', 'B', 'A', 'A', 'B', 'B', 'A',
       'A', 'A'], dtype='<U1')

In [22]:
np.where(((arr_rand <10) | (arr_rand >70)), 'A',  
         np.where(arr_rand <30, 'B', 
                  np.where(arr_rand <50, 'C','D')))

array(['A', 'B', 'C', 'A', 'A', 'A', 'B', 'A', 'B', 'D', 'A', 'A', 'B',
       'C', 'C'], dtype='<U1')

In [ ]:
np.where(arr_rand<10, 'less10', np.where(arr_rand<20, 'l20','g20'))

array(['l10', 'l20', 'g20', 'l10', 'l10', 'l20', 'l10', 'l20', 'g20',
       'l10', 'l10', 'g20', 'g20', 'g20'], dtype='<U3')

In [7]:
np.where(arr_rand <10, 'l10',np.where(arr_rand<20,'l20',
                                      np.where(arr_rand<30,'l30','g30')))

array(['l10', 'l20', 'g30', 'l10', 'l10', 'l20', 'l10', 'l20', 'g30',
       'l10', 'l10', 'l30', 'g30', 'g30'], dtype='<U3')

In [9]:
np.where(arr_rand <3,"l3",np.where(arr_rand<6,'l6',np.where(arr_rand<9,'l9','g9')))

array(['l9', 'l9', 'l6', 'l9', 'l9', 'g9', 'l6', 'l3', 'l6', 'l3', 'l3'],
      dtype='<U2')

In [13]:
# If value > 5, then yield 'gt5' else 'le5'
import numpy as np
l=[1,2,12,3,4,5,6,20,87,90,97,60,20,23,39,29,34,45,50,56,57]
nl=np.array(l)
print(nl)
#np.where(nl<=10,'G1',np.where(nl<=20,'G2',np.where(nl<=40,'G3','O')))
#np.where(nl<=10, "G1",np.where(nl<=20,"G2",np.where(nl<=30,"G3",
 #                                                  np.where(nl<=40,"G4","G5"))))

#np.where(arr_rand > 5, 'gt5', 'le5')

[ 1  2 12  3  4  5  6 20 87 90 97 60 20 23 39 29 34 45 50 56 57]


In [17]:
np.where(nl<15,"poor",np.where(nl<50,'OK',np.where(nl<75,'GOOD','Excellent')))

array(['poor', 'poor', 'poor', 'poor', 'poor', 'poor', 'poor', 'OK',
       'Excellent', 'Excellent', 'Excellent', 'GOOD', 'OK', 'OK', 'OK',
       'OK', 'OK', 'OK', 'GOOD', 'GOOD', 'GOOD'], dtype='<U9')

In [4]:
# Import data from csv file url
path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'

In [11]:
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=-900, dtype='float')

In [12]:
data

array([[  18.,    8.,  307., ...,   70.,    1., -900.],
       [  15.,    8.,  350., ...,   70.,    1., -900.],
       [  18.,    8.,  318., ...,   70.,    1., -900.],
       ...,
       [  32.,    4.,  135., ...,   82.,    1., -900.],
       [  28.,    4.,  120., ...,   82.,    1., -900.],
       [  31.,    4.,  119., ...,   82.,    1., -900.]])

In [10]:
import numpy as np
#a=r"E:\Python\Machine Learning\datasets\Auto.csv"
a=r"C:\Users\Amrita\OneDrive\Desktop\copy_desktop\Printout\ABC.csv"

In [11]:
data = np.genfromtxt(a, delimiter='|', skip_header=1, filling_values=-999)

In [12]:
data

array([[-999., -999.,   69.],
       [-999., -999.,   70.],
       [-999., -999.,   89.]])

In [19]:
data = np.genfromtxt(a, delimiter='|', skip_header=1, dtype='object')

In [20]:
data

array([[b'Anandi ', b' B.sc. ', b'69'],
       [b'NIRAJ', b' B.com', b'  70'],
       [b'SUREKHA', b' B.E. ', b' 89']], dtype=object)

In [30]:
arr_rand

array([ 8, 18, 33,  7, 77, 80, 10,  4, 12, 53,  2,  0, 20, 30, 80])

In [24]:
arr_rand.max()

np.int64(80)

In [31]:
arr_rand.max()

np.int64(80)

In [32]:
# Location of the max
print('Position of max value: ', np.argmax(arr_rand))  

Position of max value:  5


In [41]:
arr_rand

array([ 8, 18, 33,  7,  8,  8, 10,  4, 12, 53,  2,  0, 20, 30,  8])

In [42]:
arr_rand[np.argmax(arr_rand)]=8

In [43]:
arr_rand

array([ 8, 18, 33,  7,  8,  8, 10,  4, 12,  8,  2,  0, 20, 30,  8])

In [13]:
arr_rand[np.argmax(arr_rand)]

np.int64(80)

In [12]:
# Location of the min
print('Position of min value: ', np.argmin(arr_rand))  

Position of min value:  10


In [ ]:
# import and export data as a csv file
# np.genfromtxt function. It can import datasets from web URLs, 
# handle missing values, multiple delimiters, handle irregular number of columns etc.

# Turn off scientific notation
np.set_printoptions(suppress=True)  

In [ ]:
import numpy as np
l=[70,85,90,38,40,58,66]
la=np.array(l)

In [ ]:
# see first 3 rows
data[:3]

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
        -999. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
        -999. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
        -999. ]])

In [ ]:
data.shape

(392, 9)

In [ ]:
# notice all the values in last column has the same value ‘-999’?

# That happened because, `dtype=’float’`. 
# The last column in the file contained text values and since all the values in a numpy array 
# has to be of the same `dtype`, `np.genfromtxt` didn’t know how to convert it to a float.


In [ ]:
# handle datasets that has both numbers and text columns?
# set the dtype as ‘object’ or as None

In [ ]:
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype='object')
data2 = np.genfromtxt(path, delimiter=',', skip_header=1, dtype=None)
data2[:3]  # see first 3 rows

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', 'S38')])

In [24]:
data = np.genfromtxt(a, delimiter='|', skip_header=1, filling_values= -999)

In [25]:
# Save the array as a csv file
np.savetxt("C:\\Users\\Amrita\\OneDrive\\Desktop\\out.csv", data, delimiter=",")

In [35]:
data = np.arange(18)
data = data.reshape(6,3)
np.savetxt("C:\\Users\\Amrita\\OneDrive\\Desktop\\out.csv", data, delimiter=",", fmt = '%.0e')

In [ ]:
# concatenate two numpy arrays columnwise and row wise
# There are 3 different ways of concatenating two or more numpy arrays.

# Method 1: np.concatenate by changing the axis parameter to 0 and 1
# Method 2: np.vstack and np.hstack
# Method 3: np.r_ and np.c_

In [65]:
import numpy as np
a = np.zeros([4, 4])
b = np.ones([4, 4])
a, b

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]))

In [63]:
# stack the arrays vertically.
# Vertical Stack Equivalents (Row wise)
out= np.concatenate([a, b], axis=1)  

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [62]:
out

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.vstack([a,b])  

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [66]:
np.r_[a,b] 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# horizontally (columns wise)

In [34]:
# Horizontal Stack Equivalents (Coliumn wise)
np.concatenate([a, b], axis=1) 

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [ ]:
np.hstack([a,b])  

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [67]:
np.c_[a,b]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [1]:
# sort a numpy array based on one or more columns?
import numpy as np
arr = np.random.randint(1,6, size=[8, 5])
arr

array([[2, 2, 4, 3, 5],
       [5, 5, 3, 5, 5],
       [2, 5, 1, 1, 4],
       [2, 1, 3, 2, 5],
       [3, 4, 1, 5, 1],
       [3, 3, 4, 5, 4],
       [3, 1, 1, 1, 1],
       [4, 2, 4, 4, 3]], dtype=int32)

In [ ]:
# np.sort function with axis=0, all the columns will be sorted in ascending order independent 
# of eachother

In [71]:
np.mean(arr, axis=0)

array([3.625, 3.25 , 3.   , 3.25 , 1.875])

In [73]:
np.mean(arr,axis=1)

array([2.8, 2.8, 3. , 3.6, 2.8, 3.4, 2. , 3.6])

In [72]:
np.mean(arr, axis = -1)

array([2.8, 2.8, 3. , 3.6, 2.8, 3.4, 2. , 3.6])

In [77]:
arr

array([[5, 1, 3, 4, 1],
       [5, 1, 2, 5, 1],
       [2, 4, 5, 2, 2],
       [5, 5, 2, 5, 1],
       [1, 4, 4, 3, 2],
       [3, 5, 3, 2, 4],
       [3, 1, 4, 1, 1],
       [5, 5, 1, 4, 3]], dtype=int32)

In [ ]:
# Sort each columns of arr
# compromising the integrity of the row items. In simple terms, the values in each row 
# gets corrupted with values from other rows.
np.sort(arr, axis=1)

array([[1, 1, 3, 4, 5],
       [1, 1, 2, 5, 5],
       [2, 2, 2, 4, 5],
       [1, 2, 5, 5, 5],
       [1, 2, 3, 4, 4],
       [2, 3, 3, 4, 5],
       [1, 1, 1, 3, 4],
       [1, 3, 4, 5, 5]], dtype=int32)

In [19]:
# Sort each columns of arr
# compromising the integrity of the row items. In simple terms, the values in each row 
# gets corrupted with values from other rows.
np.sort(arr, axis=0)

array([[2, 1, 1, 1, 1],
       [3, 1, 1, 1, 1],
       [3, 2, 2, 2, 3],
       [4, 2, 3, 3, 3],
       [5, 3, 3, 4, 3],
       [5, 3, 3, 4, 3],
       [5, 4, 4, 5, 4],
       [5, 5, 5, 5, 5]], dtype=int32)

In [ ]:
# sort a numpy array based on 1 column using argsort?

# first understand what np.argsort does

In [ ]:
# np.argsort returns the index positions of that would make a given 1d array sorted.

In [79]:
# Get the index positions that would sort the array
x = np.array([1, 10, 5, 2, 8, 9])

sort_index = np.argsort(x)
print(sort_index)

[0 3 2 4 5 1]


In [ ]:
# In array ‘x’, the 0th item is the smallest, 3rd item is the second smallest and so on.

In [17]:
x[sort_index]

array([ 1,  2,  5,  8,  9, 10])

In [ ]:
# do an argsort on the 1st column and use the resulting index positions to sort arr.

In [82]:
arr

array([[5, 1, 3, 4, 1],
       [5, 1, 2, 5, 1],
       [2, 4, 5, 2, 2],
       [5, 5, 2, 5, 1],
       [1, 4, 4, 3, 2],
       [3, 5, 3, 2, 4],
       [3, 1, 4, 1, 1],
       [5, 5, 1, 4, 3]], dtype=int32)

In [83]:
arr[:, 0]

array([5, 5, 2, 5, 1, 3, 3, 5], dtype=int32)

In [84]:
# Argsort the first column
sorted_index_1stcol = arr[:, 2].argsort()
sorted_index_1stcol

array([7, 1, 3, 0, 5, 4, 6, 2])

In [85]:
# Sort 'arr' by first column without disturbing the integrity of rows
arr[sorted_index_1stcol]

array([[5, 5, 1, 4, 3],
       [5, 1, 2, 5, 1],
       [5, 5, 2, 5, 1],
       [5, 1, 3, 4, 1],
       [3, 5, 3, 2, 4],
       [1, 4, 4, 3, 2],
       [3, 1, 4, 1, 1],
       [2, 4, 5, 2, 2]], dtype=int32)

In [ ]:
# To sort it in decreasing order, simply reverse the argsorted index.

In [86]:
# Descending sort
arr[sorted_index_1stcol[::-1]]

array([[2, 4, 5, 2, 2],
       [3, 1, 4, 1, 1],
       [1, 4, 4, 3, 2],
       [3, 5, 3, 2, 4],
       [5, 1, 3, 4, 1],
       [5, 5, 2, 5, 1],
       [5, 1, 2, 5, 1],
       [5, 5, 1, 4, 3]], dtype=int32)

In [ ]:
sorted_index_1stcol

array([4, 5, 6, 0, 2, 3, 1, 7], dtype=int64)

In [88]:
sorted_index_1stcol[::-1]

array([2, 6, 4, 5, 0, 3, 1, 7])

In [89]:
np.flip(sorted_index_1stcol)

array([2, 6, 4, 5, 0, 3, 1, 7])

In [ ]:
sorted_index_1stcol[: :-1]

array([7, 1, 3, 2, 0, 6, 5, 4], dtype=int64)

In [ ]:
# every yth element from the list / array
a = [1,2,3,4,5,6,7,8,9]

a[::3]

[1, 4, 7]

In [ ]:
# reverses
a[:: -1]

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [ ]:
# sort a numpy array based on 2 or more columns?

# You can do this using np.lexsort by passing a tuple of columns based on which the 
# array should be sorted.

In [ ]:
# place the column to be sorted first at the rightmost side inside the tuple.

In [51]:
arr

array([[5, 3, 2, 1, 4],
       [3, 5, 3, 4, 1],
       [3, 5, 3, 4, 3],
       [5, 3, 4, 3, 2],
       [1, 3, 5, 4, 4],
       [4, 1, 3, 5, 5],
       [4, 4, 5, 4, 1],
       [4, 1, 3, 2, 5]])

In [52]:
arr1 = np.array([[2,5,8],[5,6,2],[1,2,3]])
arr1

array([[2, 5, 8],
       [5, 6, 2],
       [1, 2, 3]])

In [98]:
arr[3,:].argsort()

array([4, 2, 1, 0, 3])

In [100]:
arr[:,arr[3,:].argsort()]

array([[1, 3, 1, 5, 4],
       [1, 2, 1, 5, 5],
       [2, 5, 4, 2, 2],
       [1, 2, 5, 5, 5],
       [2, 4, 4, 1, 3],
       [4, 3, 5, 3, 2],
       [1, 4, 1, 3, 1],
       [3, 1, 5, 5, 4]], dtype=int32)

In [94]:
arr[arr[:,0].argsort()]

array([[1, 4, 4, 3, 2],
       [2, 4, 5, 2, 2],
       [3, 5, 3, 2, 4],
       [3, 1, 4, 1, 1],
       [5, 5, 2, 5, 1],
       [5, 1, 2, 5, 1],
       [5, 1, 3, 4, 1],
       [5, 5, 1, 4, 3]], dtype=int32)

In [4]:
arr

array([[2, 2, 4, 3, 5],
       [5, 5, 3, 5, 5],
       [2, 5, 1, 1, 4],
       [2, 1, 3, 2, 5],
       [3, 4, 1, 5, 1],
       [3, 3, 4, 5, 4],
       [3, 1, 1, 1, 1],
       [4, 2, 4, 4, 3]], dtype=int32)

In [9]:
# Sort by row 3, then by row 4
lexsorted_index = np.lexsort((arr[2, :], arr[1, :])) 
arr[:, lexsorted_index]

array([[4, 3, 2, 5, 2],
       [3, 5, 5, 5, 5],
       [1, 1, 2, 4, 5],
       [3, 2, 2, 5, 1],
       [1, 5, 3, 1, 4],
       [4, 5, 3, 4, 3],
       [1, 1, 3, 1, 1],
       [4, 4, 4, 3, 2]], dtype=int32)

In [6]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 3], arr[:, 1])) 
lexsorted_index

array([6, 3, 0, 7, 5, 4, 2, 1])

In [96]:
arr[lexsorted_index]

array([[3, 1, 4, 1, 1],
       [5, 1, 3, 4, 1],
       [5, 1, 2, 5, 1],
       [1, 4, 4, 3, 2],
       [2, 4, 5, 2, 2],
       [3, 5, 3, 2, 4],
       [5, 5, 2, 5, 1],
       [5, 5, 1, 4, 3]], dtype=int32)

In [21]:
arr[lexsorted_index]

array([[3, 1, 1, 1, 3],
       [3, 5, 2, 1, 1],
       [2, 1, 1, 2, 4],
       [3, 4, 4, 2, 1],
       [3, 4, 2, 2, 3],
       [1, 4, 2, 3, 3],
       [5, 4, 2, 4, 5],
       [1, 2, 1, 5, 5]], dtype=int32)

In [55]:
# Sort by column 0, then by column 1
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 2])) 

In [56]:
arr[lexsorted_index]

array([[5, 3, 2, 1, 4],
       [4, 1, 3, 5, 5],
       [4, 1, 3, 2, 5],
       [3, 5, 3, 4, 1],
       [3, 5, 3, 4, 3],
       [5, 3, 4, 3, 2],
       [1, 3, 5, 4, 4],
       [4, 4, 5, 4, 1]])

In [22]:
lexsorted_index_r = np.lexsort((arr[1, :], arr[3, :])) 

In [23]:
lexsorted_index_r

array([4, 3, 0, 1, 2])

In [27]:
arr.shape

(8, 5)

In [25]:
arr[ lexsorted_index_r]

array([[3, 5, 2, 1, 1],
       [3, 4, 4, 2, 1],
       [1, 2, 1, 5, 5],
       [3, 1, 1, 1, 3],
       [2, 1, 1, 2, 4]], dtype=int32)

In [26]:
arr[ :, lexsorted_index_r]

array([[5, 5, 1, 2, 1],
       [3, 1, 3, 1, 1],
       [4, 2, 2, 1, 1],
       [1, 2, 3, 4, 4],
       [1, 1, 3, 5, 2],
       [5, 4, 5, 4, 2],
       [3, 3, 1, 4, 2],
       [3, 2, 3, 4, 2]], dtype=int32)

In [ ]:
# Working with dates
# Numpy implements dates through the np.datetime64 object which supports a precision till 
# nanoseconds. 
# You can create one using a standard YYYY-MM-DD formatted date strings.

In [31]:
# Create a datetime64 object
date64 = np.datetime64('2018-02-04 23:00:00')
date64

numpy.datetime64('2018-02-04T23:00:00')

In [35]:
# Drop the time part from the datetime64 object
dt64 = np.datetime64(date64, 'D')
dt64

numpy.datetime64('2018-02-04')

In [33]:
dt64 = np.datetime64(date64, 'M')
dt64

numpy.datetime64('2018-02')

In [34]:
dt64 = np.datetime64(date64, 'Y')
dt64

numpy.datetime64('2018')

In [36]:
# Create the timedeltas (individual units of time)
tenminutes = np.timedelta64(10, 'm')  # 10 minutes
tenseconds = np.timedelta64(10, 's')  # 10 seconds
tennanoseconds = np.timedelta64(10, 'ns')  # 10 nanoseconds

print('Add 10 days: ', dt64 + 10)
print('Add 10 minutes: ', dt64 + tenminutes)
print('Add 10 seconds: ', dt64 + tenseconds)
print('Add 10 nanoseconds: ', dt64 + tennanoseconds)

Add 10 days:  2018-02-14
Add 10 minutes:  2018-02-04T00:10
Add 10 seconds:  2018-02-04T00:00:10
Add 10 nanoseconds:  2018-02-04T00:00:00.000000010


In [37]:
# Convert np.datetime64 back to a string
np.datetime_as_string(dt64)

'2018-02-04'

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# create a sequence of dates?
# Create date sequence
dates = np.arange(np.datetime64('2021-10-01'), np.datetime64('2021-10-10'))
print(dates)

# Check if its a business day
np.is_busday(dates)

['2021-10-01' '2021-10-02' '2021-10-03' '2021-10-04' '2021-10-05'
 '2021-10-06' '2021-10-07' '2021-10-08' '2021-10-09']


array([ True, False, False,  True,  True,  True,  True,  True, False])

In [ ]:
# vectorize – Make a scalar function work on vectors


In [ ]:
# Define a scalar function
def foo(x):
    if x % 2 == 1:
        return x**2
    else:
        return x/2

In [ ]:
# On a scalar
print('x = 10 returns ', foo(10))
print('x = 11 returns ', foo(11))

x = 10 returns  5.0
x = 11 returns  121


In [ ]:
# On a vector, doesn't work
print('x = [10, 11, 12] returns ', foo([10, 11, 12]))  # Error

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
# Vectorize foo(). Make it work on vectors.
foo_v = np.vectorize(foo, otypes=[float])

In [ ]:
print('x = [10, 11, 12] returns \n',              foo_v([10, 11, 12]))
print('x = [[10, 11, 12], [1, 2, 3]] returns \n', foo_v([[10, 11, 12], [1, 2, 3]]))

x = [10, 11, 12] returns 
 [  5. 121.   6.]
x = [[10, 11, 12], [1, 2, 3]] returns 
 [[  5. 121.   6.]
 [  1.   1.   9.]]


In [ ]:
# apply_along_axis – Apply a function column wise or row wise

In [ ]:
# Create a 4x10 random array
np.random.seed(100)
arr_x = np.random.randint(1,10,size=[4,10])
arr_x

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5],
       [2, 6, 4, 5, 5, 4, 8, 2, 2, 8],
       [8, 1, 3, 4, 3, 6, 9, 2, 1, 8]])

In [ ]:
# find the difference of the maximum and the minimum value in each row?

In [ ]:
# the normal approach would be to write a for-loop that iterates along each row and 
# then compute the max-min in each iteration.

In [ ]:
# That sounds alright but it can get cumbersome if you want to do the same column wise

In [ ]:
# using the numpy.apply_along_axis

In [ ]:
# It takes as arguments:

# Function that works on a 1D vector (fund1d)
# Axis along which to apply func1d. For a 2D array, 1 is row wise and 0 is column wise.
# Array on which func1d should be applied.

In [ ]:
# Define func1d
def max_minus_min(x):
    return np.max(x) - np.min(x)

In [ ]:
# Apply along the rows
print('Row wise: ', np.apply_along_axis(max_minus_min, 1, arr=arr_x))

Row wise:  [8 8 6 8]


In [ ]:
# Apply along the columns
print('Column wise: ', np.apply_along_axis(max_minus_min, 0, arr=arr_x))

Column wise:  [7 8 2 7 6 5 8 5 5 5]


In [ ]:
# What is missing in numpy?
# So far we have covered a good number of techniques to do data manipulations with numpy. 
# But there are a considerable number of things you can’t do with numpy directly. 

# No direct function to merge two 2D arrays based on a common column.
# Create pivot tables directly
# No direct way of doing 2D cross tabulations.
# No direct method to compute statistics (like mean) grouped by unique values in an array.
# And more..

# pandas is the answer.