In [2]:
a= [1,2,"four", 3.5]
b=[10,20,'asd',4.5]
a+b

[1, 2, 'four', 3.5, 10, 20, 'asd', 4.5]

In [3]:
list(zip(a,b))

[(1, 10), (2, 20), ('four', 'asd'), (3.5, 4.5)]

In [3]:
import numpy as np
arr1 = np.array(a)
arr2 = np.array(b)

In [4]:
arr1

array(['1', '2', 'four', '3.5'], dtype='<U32')

In [11]:
l1 = np.array(range(20,30)) 
l1, type(l1)

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), numpy.ndarray)

In [13]:
arr3 = np.arange(2,10)

arr3.dtype, type(arr3)

(dtype('int64'), numpy.ndarray)

In [14]:
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
l1 = ['a', 'b', 'c','d']
a2 = np.array(l1)
a2, type(a2), a2.dtype

(array(['a', 'b', 'c', 'd'], dtype='<U1'), numpy.ndarray, dtype('<U1'))

In [21]:
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2 = arr3.astype(float)
arr2

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [5]:
a1=[1,2,3,4,5]
a2=[10,20,30,40,50]


In [7]:
b1=np.array(a1)
b2=np.array(a2)
print(b1)
print(b2)

[1 2 3 4 5]
[10 20 30 40 50]


In [8]:
type(b1)

numpy.ndarray

In [9]:
b1+b2

array([11, 22, 33, 44, 55])

In [24]:
np.astype(arr3, 'float') 

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
#arr1+arr2

In [3]:
np.array(a)

array(['1', '2', 'four', '3.5'], dtype='<U11')

In [5]:
b=[]
for i in a:
    print(i+i)
    b.append(i+i)

2
4
fourfour
7.0


In [6]:
b

[2, 4, 'fourfour', 7.0]

In [2]:
import numpy as np
import sys
 
# NumPy is pure gold. It is fast, easy to learn, feature-rich, and 
# therefore at the core of almost all popular scientific packages in the 
# Python universe (including SciPy and Pandas, two most widely used packages
# for data science and statistical modeling). 
# LISTs are good, you can change values but you cannot apply mathematical 
# functions
## Faster & needs low space

In [27]:
distance = [10, 12, 18, 16]
time     = [1,   2,  3,  10]
########## [10+1 , 12+2, 18+3, 16+10]
a=distance / time
a

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [12]:
speed = distance / time
speed

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [4]:
type(distance)

list

In [5]:
np_distance = np.array(distance)
np_time     = np.array(time)

In [6]:
type(np_distance)

numpy.ndarray

In [7]:
type(time), type(np_time)

(list, numpy.ndarray)

In [8]:
np_time

array([ 1,  2,  3, 10])

In [8]:
np_time
type(np_time)

numpy.ndarray

In [6]:
np_time.dtype

dtype('int32')

In [7]:
speed = np_distance/np_time
speed

array([10. ,  6. ,  6. ,  1.6])

In [8]:
type(speed)

numpy.ndarray

In [15]:
speed.dtype

dtype('float64')

In [18]:
speed.astype(int)

array([10,  6,  6,  1])

In [ ]:
# why use numpy
# compare numpy array with standard python LIST type array

In [ ]:
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
range(10,25,2)

range(10, 25, 2)

In [25]:
range(10)

range(0, 10)

In [12]:
np.arange(10, 30,4)

array([10, 14, 18, 22, 26])

In [6]:
data = range(100)
print(type(data))
data = np.array(data)

<class 'range'>


In [7]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
data = range(1000)

In [29]:
d=np.array(data)
print(type(d), d.dtype )


<class 'numpy.ndarray'> int32


In [35]:
len('sdfghjklertyuiodcvbnm ')

22

In [36]:
var = np.array(["ascf34ed",'edc',"60.78", "sdfghjklertyu"])
print(var, type(var))
var.dtype

['ascf34ed' 'edc' '60.78' 'sdfghjklertyu'] <class 'numpy.ndarray'>


dtype('<U13')

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
len(data)

1000

In [34]:
import sys, numpy as np
sys.getsizeof(1234557890)

32

In [37]:
sys.getsizeof(86767676789.987965457)

24

In [40]:
sys.getsizeof('asrtyuio')

49

In [50]:
sys.getsizeof(123456789)

28

In [16]:
arr3.shape

(8,)

In [44]:
arr3.ndim
##len(d)
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
len(arr3)

8

In [42]:
arr3.size

8

In [46]:
arr3.itemsize

8

In [48]:
sys.getsizeof(7) *(arr3.size)

224

In [49]:
arr3

array([2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr3.itemsize

8

In [38]:
sys.getsizeof(arr3)

176

In [51]:
# PYTHON LIST
data = range(10000)

print(sys.getsizeof(1000)*len(data))

# NUMPY ARRAY
data_np = np.arange(10000)


280000


In [52]:
data_np.size

10000

In [49]:
data_np.size * data_np.itemsize

80000

In [15]:
data_np.itemsize

4

In [23]:
print(data_np.size, data_np.itemsize)
print(data_np.size * data_np.itemsize)

array([ 10, 120,  30])

In [ ]:
# The above output shows that the memory allocated by list is 28000 whereas the 
# memory allocated by the numpy array is just 4000. 
# From this, you can conclude that there is a major difference between the two and 
# this makes python numpy array as the preferred choice over list.

In [22]:
### Example - getsizeof
print('Integer memory size : ', sys.getsizeof(5) )
## increase size with incearse in digits
print('Integer memory size : ', sys.getsizeof(566666666) )
print('Integer memory size : ', sys.getsizeof(5666666954) )
print('Float   memory size : ', sys.getsizeof(5.05) )
print('Float   memory size : ', sys.getsizeof(51111111.05858588522) )

print('\nString  memory size : ', sys.getsizeof('5') )
print('String  memory size : ', sys.getsizeof('A') )
print('String  memory size : ', sys.getsizeof('Ab') )
print('String  memory size : ', sys.getsizeof('AAA') )
print('String  memory size : ', sys.getsizeof('AAAA') )
print('String  memory size AAAAA : ', sys.getsizeof('AAAAA') )

Integer memory size :  28
Integer memory size :  28
Integer memory size :  32
Float   memory size :  24
Float   memory size :  24

String  memory size :  50
String  memory size :  50
String  memory size :  51
String  memory size :  52
String  memory size :  53
String  memory size AAAAA :  54


In [32]:
a = [1,2,3,4,5]
b= [10,11,12,13,14,15]
x = zip(a,b)
list(x)

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]

In [1]:
import numpy as np

In [53]:
import time
import sys
 
SIZE = 1000000
 
L1= range(SIZE)
L2= range(SIZE)
A1= np.arange(SIZE)
A2=np.arange(SIZE)
 
start= time.time()
result=[x+y for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
 
start=time.time()
result= A1+A2
print((time.time()-start)*1000)

880.1822662353516
165.18592834472656


In [6]:
s =time.time()
[(x,y) for x,y in zip(L1,L2)]
time.time() - s

0.2831435203552246

In [ ]:
SIZE = 5
L1= range(SIZE)
L2= range(SIZE)
[(x,y) for x,y in zip(L1,L2)]

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

In [ ]:
np_arr = np.arange(1000000)
normal_arr = list(range(1000000))


In [ ]:
%%time 
# loop using numpy array
for i in range(5):
    np_arr2 = np_arr * 2

Wall time: 15.6 ms


In [ ]:
%%time 
# loop using normal python array, list
for i in range(5):
    normal_arr2 = [x * 2 for x in normal_arr]
    
  
a= 10
b= 60
for i in range(100):
    c= a+b

Wall time: 692 ms


In [ ]:
print(np_arr2)

[      0       2       4 ... 1999994 1999996 1999998]


In [ ]:
# NumPy-based algorithms are generally 10 to 100 times faster (or more) 
# than their pure Python counterparts and use significantly less memory.

In [ ]:
# NDIM

In [54]:
import numpy as np

In [51]:
oned = np.array([1,2,3,4])
oned.shape, oned.ndim

((4,), 1)

In [12]:
one_d= np.array([1,3,4,5])
one_d.ndim

1

In [14]:
two=np.array([[1,2,3,4],[1,2,3,4]])
two.ndim

2

In [58]:
oned = np.array([[1,2,3], [10,np.nan,30], [1,2,3], [5,3,4]])
print(oned)
oned.shape, oned.ndim, oned.size

[[ 1.  2.  3.]
 [10. nan 30.]
 [ 1.  2.  3.]
 [ 5.  3.  4.]]


((4, 3), 2, 12)

In [57]:
type(oned)

numpy.ndarray

In [59]:
type(np.nan)

float

In [56]:
oned

array([[ 1.,  2.,  3.,  4., nan],
       [ 2.,  5., nan,  7.,  4.],
       [ 2.,  5.,  8.,  3.,  9.]])

In [65]:
oned = np.array([[[[1,2],[3,4]], [[2,1],[3,4]]], [[[1,2],[3,4]], [[2,1],[3,4]]]])
print(oned)
oned.ndim

[[[[1 2]
   [3 4]]

  [[2 1]
   [3 4]]]


 [[[1 2]
   [3 4]]

  [[2 1]
   [3 4]]]]


4

In [60]:
two = np.array([[[[19,22,60],[10,20,6],[50,9,45],[10,29,15]],
                [[39,62,10],[15,80,16],[53,19,45],[10,29,15]]],
               [[[19,22,60],[10,20,6],[50,9,45],[10,29,15]],
                [[39,62,10],[15,80,16],[53,19,45],[10,29,15]]]])
print(two.shape)
print(two.ndim)

(2, 2, 4, 3)
4


In [78]:
two.itemsize

8

In [61]:
two

array([[[[19, 22, 60],
         [10, 20,  6],
         [50,  9, 45],
         [10, 29, 15]],

        [[39, 62, 10],
         [15, 80, 16],
         [53, 19, 45],
         [10, 29, 15]]],


       [[[19, 22, 60],
         [10, 20,  6],
         [50,  9, 45],
         [10, 29, 15]],

        [[39, 62, 10],
         [15, 80, 16],
         [53, 19, 45],
         [10, 29, 15]]]])

In [61]:
a=np.array([[[[1,2],[4,7]],[[5,3],[5,3]]],  [[[10,20],[40,70]],[[50,30],[15,13]]]])
print(a.ndim)
print(a.itemsize)
print(a.shape)
a

4
4
(2, 2, 2, 2)


array([[[[ 1,  2],
         [ 4,  7]],

        [[ 5,  3],
         [ 5,  3]]],


       [[[10, 20],
         [40, 70]],

        [[50, 30],
         [15, 13]]]])

In [51]:
10,20,300,549

(2, 2, 3)

In [1]:
import numpy as np
'''
a= np.array([[[23,12],[45,6]],
             [[7,3],[12,43]],
             [[23,1],[12,23]]])
'''
a = np.array([[1,2,3,4], [4,5,7,8], [4,5,3,6]], dtype=str)
print(a)

print(type(a))
print(a.ndim)     # number of dimensions in the array
print(a.itemsize) # So every element occupies 4 byte in the above numpy array.
print(a.size)
print(a.shape)
a.dtype

[['1' '2' '3' '4']
 ['4' '5' '7' '8']
 ['4' '5' '3' '6']]
<class 'numpy.ndarray'>
2
4
12
(3, 4)


dtype('<U1')

In [49]:
a=np.array([[[[1,2,3,4],[10,20,30,40]],
            [[1,2,3,4],[10,20,30,40]]],
           [[[-1,-2,-3,-4],[-10,-20,-30,-40]],
            [[1,2,3,4],[10,20,30,40]]]])


In [50]:
a.ndim

4

In [51]:
a.shape

(2, 2, 2, 4)

In [52]:
a

array([[[[  1,   2,   3,   4],
         [ 10,  20,  30,  40]],

        [[  1,   2,   3,   4],
         [ 10,  20,  30,  40]]],


       [[[ -1,  -2,  -3,  -4],
         [-10, -20, -30, -40]],

        [[  1,   2,   3,   4],
         [ 10,  20,  30,  40]]]])

In [11]:
dimension  = np.array([[[1,2,3,4],[4,3,2,1]],
                       [[5,6,7,8],[5,4,3,2]]
                       ])
print(dimension)
dimension.ndim

[[[1 2 3 4]
  [4 3 2 1]]

 [[5 6 7 8]
  [5 4 3 2]]]


3

In [ ]:
.a

array([[[1, 2, 3, 4],
        [4, 5, 3, 6],
        [4, 5, 3, 6]]])

In [ ]:
# linespace
# Equally-spaced numbers

In [21]:
np.linspace(1, 6, 5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [45]:
np.linspace(1, 16, 6)

array([ 1.,  4.,  7., 10., 13., 16.])

In [7]:
np.linspace(1, 16, 8)

array([ 1.        ,  3.14285714,  5.28571429,  7.42857143,  9.57142857,
       11.71428571, 13.85714286, 16.        ])

In [ ]:
# Random
# The random module provides functions to generate random numbers 
# (and also statistical distributions) of any given shape.

# numpy.random.randn generates samples from the normal distribution, 
# numpy.random.rand  generates samples from the unifrom (in range [0,1)).

In [72]:
np.random.randn()

-0.882703301561273

In [22]:
np.full((2,3),200)

array([[200, 200, 200],
       [200, 200, 200]])

In [24]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [1]:
import numpy as np
# Random numbers between [0,1) of shape 2,3
print(np.random.rand(4,5))

[[0.96472569 0.28975338 0.92999166 0.63341309 0.53877716]
 [0.24740102 0.79130702 0.97092922 0.72456257 0.53176374]
 [0.84669316 0.19564494 0.65317821 0.30797451 0.86527723]
 [0.70228397 0.16802327 0.8691973  0.24212997 0.83177595]]


In [4]:
print(np.random.randn(2, 3))

[[-2.06739803 -1.67840591  1.77525361]
 [-0.53815862  1.4281399  -1.86513498]]


In [11]:
print(np.random.randint( 10))

5


In [36]:
print(np.random.randint(14, 100, size=[2,3]))

[[91 52 47]
 [36 72 55]]


In [71]:
 # np.random.seed(8)
np.random.random(8)

array([0.0389123 , 0.44642291, 0.18817252, 0.62705565, 0.2153178 ,
       0.15097011, 0.53614431, 0.10038679])

In [6]:
import numpy as np
np.random.seed(100000000)
np.random.rand(3,4)

array([[0.9573673 , 0.63919974, 0.21122547, 0.24391104],
       [0.11789441, 0.59868977, 0.89777328, 0.93083971],
       [0.81338718, 0.91537738, 0.76244417, 0.90855475]])

In [86]:
np.random.seed(3)
np.random.rand(4,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322]])

In [100]:
np.random.seed(55)
print(np.random.randint(14, 600, size=[4,3]))

[[475 309 555]
 [ 51 361  68]
 [382 561 364]
 [475 557 449]]


In [73]:
arr = np.random.randint(14, 100, size=[2,3])
arr

array([[47, 82, 47],
       [22, 16, 90]], dtype=int32)

In [74]:
arr

array([[47, 82, 47],
       [22, 16, 90]], dtype=int32)

In [68]:
# One random number between [0, 1)
#np.random.seed(100)
print(np.random.random(10))

[0.26843898 0.4998825  0.67923    0.80373904 0.38094113 0.06593635
 0.2881456  0.90959353 0.21338535 0.45212396]


In [50]:
np.random.random()

0.5300038886795768

In [42]:
# Random numbers between [0,1) of shape 2,2
import numpy as np
np.random.seed(2000)
print(np.random.random(size=[4, 2]))
print(np.random.random(size=[4, 2]))

[[0.57051729 0.56452876]
 [0.48844183 0.33647775]
 [0.37586818 0.53203587]
 [0.06810629 0.58452906]]
[[0.23789776 0.16075658]
 [0.15211915 0.12706922]
 [0.32744117 0.69415387]
 [0.35896647 0.89136566]]


In [83]:
np.random.normal()

5.28782355120913

In [20]:
# Pick 10 items from a given list, with equal probability
#np.random.seed(700)
print(np.random.choice(['deepak', 'raj', 'rakesh', 'owl', 'monkey'],
                        size=10, replace=True))  

['deepak' 'deepak' 'owl' 'rakesh' 'deepak' 'monkey' 'deepak' 'rakesh'
 'owl' 'deepak' 'raj' 'monkey' 'raj' 'monkey' 'raj']


In [24]:
# Pick 10 items from a given list, with equal probability
np.random.seed(7)
print(np.random.choice(['deepak', 'raj', 'rakesh', 'owl', 'monkey'], size=3, replace=True))  
print(np.random.choice(['deepak', 'raj', 'rakesh', 'owl', 'monkey'], size=3, replace=False))  

['monkey' 'raj' 'owl']


ValueError: Cannot take a larger sample than population when 'replace=False'

In [ ]:
# If you want to repeat the same set of random numbers every time, you need to set the seed 
# or the random state. The see can be any value. The only requirement is you must set the seed 
# to the same value every time you want to generate the same set of random numbers.

# Once np.random.RandomState is created, all the functions of the np.random module becomes 
# available to the created randomstate object.

In [72]:
# Create the random state
rn = np.random.RandomState(100)
print(rn.rand(3,2),end="\n---------\n")
print(rn.rand(3,2),end="\n---------\n")
new=np.random.RandomState(1)
# Create random numbers between [0,1) of shape 2,2
print(new.rand(3,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]
 [0.00471886 0.12156912]]
---------
[[0.67074908 0.82585276]
 [0.13670659 0.57509333]
 [0.89132195 0.20920212]]
---------
[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02]]


In [73]:
rn.rand(3,2)

array([[0.18532822, 0.10837689],
       [0.21969749, 0.97862378],
       [0.81168315, 0.17194101]])

In [70]:
# Set the random seed
np.random.seed(1)

# Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))
print(np.random.rand(2,2))

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]
[[0.14675589 0.09233859]
 [0.18626021 0.34556073]]


In [ ]:
np.random.seed(6)

print(np.random.rand(2,2))
print(np.random.rand(2,2))

[[0.89286015 0.33197981]
 [0.82122912 0.04169663]]
[[0.10765668 0.59505206]
 [0.52981736 0.41880743]]


In [ ]:
a=(10,20)

In [ ]:
a=10,20

In [26]:
np.random.randint(10)

1

In [26]:
# How to get the unique items and the counts?
# The np.unique method can be used to get the unique items. 
# If you want the repetition counts of each item, set the return_counts parameter to True.

# Create random integers of size 10 between [0,10)
import numpy as np
np.random.seed(3)

arr_rand = np.random.randint(10, 15, size=10)
print(arr_rand)
print(type(arr_rand))

[12 10 11 13 10 10 10 13 12 13]
<class 'numpy.ndarray'>


In [27]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts= True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

Unique items :  [10 11 12 13]
Counts       :  [4 1 2 3]


In [28]:
# Get the unique items and their counts
uniqs = np.unique(arr_rand, return_counts= False)
print("Unique items : ", uniqs)
#print("Counts       : ", counts)

Unique items :  [10 11 12 13]


In [31]:
def inp(a,b):
    return a+b, a-b, a*b, a/b

In [34]:
v = inp(30,20)
v

(50, 10, 600, 1.5)

In [36]:
v[2]

600

In [29]:
# Get the unique items and their counts
uniqs= np.unique([1,1,1,12,2,2,2,3,3,23,12], return_counts= True)
print(uniqs)
print("Unique items : ", uniqs[0] )
print("Counts       : ", uniqs[1])

(array([ 1,  2,  3, 12, 23]), array([3, 3, 2, 2, 1]))
Unique items :  [ 1  2  3 12 23]
Counts       :  [3 3 2 2 1]


In [80]:
uniqs

(array([ 1,  2,  3, 12, 23]), array([3, 3, 2, 2, 1], dtype=int64))

In [81]:
uniqs[0]

array([ 1,  2,  3, 12, 23])

In [82]:
uniqs[1]

array([3, 3, 2, 2, 1], dtype=int64)

In [83]:
# Normal distribution with mean=0 and variance=1
data = np.random.randn(4,3)
data

array([[-0.2773882 , -0.35475898, -0.08274148],
       [-0.62700068, -0.04381817, -0.47721803],
       [-1.31386475,  0.88462238,  0.88131804],
       [ 1.70957306,  0.05003364, -0.40467741]])

In [37]:
data = np.random.randint(0, 5, size = (4,3) )
data

array([[1, 1, 2],
       [0, 4, 4],
       [0, 2, 1],
       [2, 2, 2]], dtype=int32)

In [23]:
data.mean()

np.float64(1.75)

In [38]:
## row wise column average
data.mean(axis=1)

array([1.33333333, 2.66666667, 1.        , 2.        ])

In [39]:
### column wise row average
data.mean(axis=0)

array([0.75, 2.25, 2.25])

In [24]:
type(data)

numpy.ndarray

In [27]:
data.dtype

dtype('int32')

In [28]:
data1 = data.astype('str')

In [29]:
data1.dtype

dtype('<U11')

In [30]:
data1

array([['0', '1', '2'],
       ['2', '0', '4'],
       ['0', '4', '0'],
       ['3', '2', '3']], dtype='<U11')

In [ ]:
type(data)

numpy.ndarray

In [138]:
np.mean(data)

4.166666666666667

In [139]:
data.mean()

4.166666666666667

In [81]:
data.mean(axis=1)

array([8.        , 4.66666667, 5.        , 8.33333333])

In [73]:
data.var()

1.2423018819442122

In [85]:
# creating ndarray
data1 = [6, 7.1, 85, 0, 1]

In [86]:
arr1 = np.array(data1)

In [87]:
arr1

array([ 6. ,  7.1, 85. ,  0. ,  1. ])

In [141]:
# nested array
data2 = [[1, 2.3, 3, 4], [5, 6, 7, 8]]

In [142]:
arr2 = np.array(data2)
arr2

array([[1. , 2.3, 3. , 4. ],
       [5. , 6. , 7. , 8. ]])

In [90]:
arr2.shape

(2, 4)

In [16]:
arr2.ndim

2

In [17]:
arr2.dtype

dtype('float64')

In [31]:
data=np.array([[1,2,0,],[0,0,3],[6,3,8]])
data

array([[1, 2, 0],
       [0, 0, 3],
       [6, 3, 8]])

In [32]:
p = np.zeros_like(data)
p

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [87]:
p1= np.ones_like(data)
p1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [88]:
p2= np.full((2,4),7)
p2

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [45]:
a= np.eye(4)
a*3

array([[3., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 3.]])

In [46]:
a.dtype

dtype('float64')

In [ ]:
# other methods of creating arrays

In [112]:
# zeros
a = np.zeros((10,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [94]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.zeros_like(arr2)
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
# ones
a = np.ones(10)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [107]:
b = np.ones((3, 6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [108]:
c = np.ones_like(q)
c

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [112]:
np.full((2,4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [35]:
# arange
a = np.arange(15,60,3)
a

array([15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57])

In [38]:
a[a>40]

array([42, 45, 48, 51, 54, 57])

In [81]:
a[a>35]

array([36, 39, 42, 45, 48, 51, 54, 57])

In [116]:
a.dtype

dtype('int32')

In [103]:
# convert the data type
b = a.astype(np.float64)
b

array([15., 18., 21., 24., 27., 30., 33., 36., 39., 42., 45., 48., 51.,
       54., 57.])

In [ ]:
# Arithmetic with NumPy Arrays
# Any arithmetic operations between equal-size arrays applies the 
# operation element-wise:

In [47]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [53]:
arr+10

array([[11., 12., 13.],
       [14., 15., 16.]])

In [43]:
arr1 =arr + 10
arr1

array([[11., 12., 13.],
       [14., 15., 16.]])

In [140]:
arr + arr

array([[22., 24., 26.],
       [28., 30., 32.]])

In [141]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import numpy as np

In [ ]:
# Comparisons between arrays of the same size yield boolean arrays:
arr2 = np.array([[100, 4.5, '1',5], [7,12, 2, 120],[12,2,8,5],[6,34,2,9]])
arr2

array([['100', '4.5', '1', '5'],
       ['7', '12', '2', '120'],
       ['12', '2', '8', '5'],
       ['6', '34', '2', '9']], dtype='<U32')

In [109]:
arr2.shape

(4, 6)

In [54]:
import numpy as np
arr2 =np.random.randint(2,20, [4,6])

In [55]:
arr2

array([[ 3,  7, 10, 16,  3, 12],
       [ 9, 13,  3, 17, 18,  7],
       [19, 16,  2,  2, 11,  7],
       [ 9,  7, 16,  3, 19,  3]], dtype=int32)

In [59]:
arr2[arr2>10]

array([16, 12, 13, 17, 18, 19, 16, 11, 16, 19], dtype=int32)

In [74]:
arr2[ ::-1,  ::-1 ]

array([[ 3, 19,  3, 16,  7,  9],
       [ 7, 11,  2,  2, 16, 19],
       [ 7, 18, 17,  3, 13,  9],
       [12,  3, 16, 10,  7,  3]], dtype=int32)

In [51]:
arr2[0:2 , 0:3]

array([[14,  7, 18],
       [16,  8,  6]], dtype=int32)

In [120]:
arr2[ sr: er-1, sc: ec-1]

NameError: name 'sr' is not defined

In [56]:
arr2[:2 ]

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5]], dtype=int32)

In [57]:
arr2[:2,:]

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5]], dtype=int32)

In [58]:
arr2[:2,0:]

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5]], dtype=int32)

In [62]:
arr2[0:2, 0:10]

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5]], dtype=int32)

In [63]:
arr2

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5],
       [ 5, 10, 18,  3,  2, 18],
       [14,  9, 12, 11,  5,  2]], dtype=int32)

In [64]:
arr2[1,2]

np.int32(6)

In [116]:
arr2[:2, : 2]

array([[ 2, 18],
       [12, 18]])

In [119]:
arr2[1:3, 1:4]

array([[18, 18, 14],
       [18,  4,  9]])

In [75]:
arr2

array([[ 3,  7, 10, 16,  3, 12],
       [ 9, 13,  3, 17, 18,  7],
       [19, 16,  2,  2, 11,  7],
       [ 9,  7, 16,  3, 19,  3]], dtype=int32)

In [77]:
arr2[:2,[1,-2]]

array([[ 7,  3],
       [13, 18]], dtype=int32)

In [112]:
arr2[:2,1:4]

array([[13, 12, 18],
       [14, 14, 18]])

In [68]:
arr2

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5],
       [ 5, 10, 18,  3,  2, 18],
       [14,  9, 12, 11,  5,  2]], dtype=int32)

In [ ]:
arr2[]

In [122]:
arr2[[0,2,-1],:]

array([[ 2, 18, 11,  3, 17, 13],
       [14, 18,  4,  9,  3,  5],
       [15,  3,  4,  5, 19, 13]])

In [89]:
arr2

array([[ 3,  7, 10, 16,  3, 12],
       [ 9, 13,  3, 17, 18,  7],
       [19, 16,  2,  2, 11,  7],
       [ 9,  7, 16,  3, 19,  3]], dtype=int32)

In [100]:
arr2

array([[ 3,  7, 10, 16,  3, 12],
       [ 9, 13,  3, 17, 18,  7],
       [19, 16,  2,  2, 11,  7],
       [ 9,  7, 16,  3, 19,  3]], dtype=int32)

In [105]:
arr2[::-1,::-1][-3:,]

array([[ 7, 11,  2,  2, 16, 19],
       [ 7, 18, 17,  3, 13,  9],
       [12,  3, 16, 10,  7,  3]], dtype=int32)

In [101]:
arr2[-3:,:][::-1, ::-1]

array([[ 3, 19,  3, 16,  7,  9],
       [ 7, 11,  2,  2, 16, 19],
       [ 7, 18, 17,  3, 13,  9]], dtype=int32)

In [111]:
a3 = arr2[:, :4]
a3

array([[ 3,  7, 10, 16],
       [ 9, 13,  3, 17],
       [19, 16,  2,  2],
       [ 9,  7, 16,  3]], dtype=int32)

In [120]:
a3[[0,1,2,3],[0,1,2,3]]

array([ 3, 13,  2,  3], dtype=int32)

In [114]:
a3.diagonal()

array([ 3, 13,  2,  3], dtype=int32)

In [ ]:
np.fliplr(a3).diagonal()

array([16,  3, 16,  9], dtype=int32)

In [123]:
np.flipud(a3).diagonal()

array([ 9, 16,  3, 16], dtype=int32)

In [92]:
arr2[::-1,]

array([[ 9,  7, 16,  3, 19,  3],
       [19, 16,  2,  2, 11,  7],
       [ 9, 13,  3, 17, 18,  7],
       [ 3,  7, 10, 16,  3, 12]], dtype=int32)

In [135]:
arr2[1,0] , arr2[-1,-1]

(6, 2)

In [137]:
arr2[[1,3],[0,-1]]

array([6, 2])

In [69]:
arr2[-1:-3, -2:-5]

array([], shape=(0, 0), dtype=int32)

In [142]:
np.array([arr2[[1,3], 2] , arr2[[1,3],4]])

array([[14,  9],
       [ 4, 13]])

In [ ]:
arr2[[list_row_num], [list_col_num]]

In [138]:
arr2[st_row: end_row-1,  col_sta: col_end-1]

NameError: name 'st_row' is not defined

In [86]:
arr2

array([[14,  7, 18,  2,  4, 11],
       [16,  8,  6, 16, 11,  5],
       [ 5, 10, 18,  3,  2, 18],
       [14,  9, 12, 11,  5,  2]], dtype=int32)

In [87]:
arr2[:,2]

array([18,  6, 18, 12], dtype=int32)

In [78]:
arr2

array([[14,  7, 28,  2,  4, 11],
       [16,  8, 16, 16, 11,  5],
       [ 5, 10, 28,  3,  2, 18],
       [14,  9, 22, 11,  5,  2]], dtype=int32)

In [ ]:
arr2[:, 4]  =arr2[:, 4] +100

array([104, 111, 102, 105], dtype=int32)

In [72]:
arr2[:, 2] +10

array([28, 16, 28, 22], dtype=int32)

In [74]:
arr2[:,2] = arr2[:,2] +10
arr2

array([[14,  7, 28,  2,  4, 11],
       [16,  8, 16, 16, 11,  5],
       [ 5, 10, 28,  3,  2, 18],
       [14,  9, 22, 11,  5,  2]], dtype=int32)

In [88]:
arr2[:,2 ] =arr2[:,2]+10

In [89]:
arr2

array([[14,  7, 28,  2,  4, 11],
       [16,  8, 16, 16, 11,  5],
       [ 5, 10, 28,  3,  2, 18],
       [14,  9, 22, 11,  5,  2]], dtype=int32)

In [20]:
arr2[ 3 , : ]

array([ 6., 34., 12.,  9.])

In [4]:
arr2[:,:]

array([[16, 13,  9,  2, 13, 16],
       [19,  6,  2,  9,  7,  9],
       [ 5, 11, 14, 16, 18,  8],
       [ 4, 14,  3,  8, 12, 12]], dtype=int32)

In [3]:
arr2.T

array([[16, 19,  5,  4],
       [13,  6, 11, 14],
       [ 9,  2, 14,  3],
       [ 2,  9, 16,  8],
       [13,  7, 18, 12],
       [16,  9,  8, 12]], dtype=int32)

In [6]:
a1=arr2.T
a1

array([[16, 19,  5,  4],
       [13,  6, 11, 14],
       [ 9,  2, 14,  3],
       [ 2,  9, 16,  8],
       [13,  7, 18, 12],
       [16,  9,  8, 12]], dtype=int32)

In [13]:
arr2

array([[16, 13,  9,  2, 13, 16],
       [19,  6,  2,  9,  7,  9],
       [ 5, 11, 14, 16, 18,  8],
       [ 4, 14,  3,  8, 12, 12]], dtype=int32)

In [11]:
arr2 [::-1,:]

array([[ 4, 14,  3,  8, 12, 12],
       [ 5, 11, 14, 16, 18,  8],
       [19,  6,  2,  9,  7,  9],
       [16, 13,  9,  2, 13, 16]], dtype=int32)

In [16]:
arr2[::-1,::-1]

array([[12, 12,  8,  3, 14,  4],
       [ 8, 18, 16, 14, 11,  5],
       [ 9,  7,  9,  2,  6, 19],
       [16, 13,  2,  9, 13, 16]], dtype=int32)

In [17]:
arr2

array([[16, 13,  9,  2, 13, 16],
       [19,  6,  2,  9,  7,  9],
       [ 5, 11, 14, 16, 18,  8],
       [ 4, 14,  3,  8, 12, 12]], dtype=int32)

In [18]:
arr2[::-2,:]

array([[ 4, 14,  3,  8, 12, 12],
       [19,  6,  2,  9,  7,  9]], dtype=int32)

In [19]:
arr2[::-3,:]

array([[ 4, 14,  3,  8, 12, 12],
       [16, 13,  9,  2, 13, 16]], dtype=int32)

In [35]:
arr+arr2

ValueError: operands could not be broadcast together with shapes (2,3) (4,4) 

In [39]:
arr2

array([[100. ,   4.5,  11. ,   5. ],
       [  7. ,  12. ,  12. , 120. ],
       [ 12. ,   2. ,  18. ,   5. ],
       [  6. ,  34. ,  12. ,   9. ]])

In [42]:
arr2[arr2>10]

array([100.,  11.,  12.,  12., 120.,  12.,  18.,  34.,  12.])

In [166]:
arr, arr2


(array([[11., 12., 13.],
        [14., 15., 16.]]),
 array([[100.,   4.,   1.,   5.],
        [  7.,  12.,   2., 120.],
        [ 12.,   2.,   8.,   5.],
        [  6.,  34.,   2.,   9.]]))

In [65]:
arr2[2,0]

12.0

In [167]:
arr2[arr2 > arr]

ValueError: operands could not be broadcast together with shapes (4,4) (2,3) 

In [4]:
arr = np.array([[11,12,13],[14,5,16]])
arr

array([[11, 12, 13],
       [14,  5, 16]])

In [10]:
import numpy as np
threeD=np.array([[10,12,13],[20,32,34]])
threeD.shape

(2, 3)

In [12]:
d3 = np.array([[2,5, 1,8],[2,5, 8 ,9 ]])
d3.shape

(2, 4)

In [ ]:
[threeD > 25]

array([[False, False, False],
       [False,  True,  True]])

In [11]:
d3[threeD > 25]

IndexError: boolean index did not match indexed array along axis 1; size of axis is 4 but size of corresponding boolean axis is 3

In [11]:
arr[threeD > arr]

array([14,  5, 16])

In [47]:
arr[threeD > arr]

array([14., 15., 16.])

In [ ]:
ac=np.array([12,23,42,12])

In [13]:
# Basic Indexing and Slicing
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr[5]

np.int64(15)

In [15]:
arr[5:8]

array([15, 16, 17])

In [16]:
arr[7]=70

In [17]:
arr

array([10, 11, 12, 13, 14, 15, 16, 70, 18, 19])

In [23]:
# broadcasting a value to multiple array positions
arr[5:8]= [200,300,400]

In [20]:
arr[5:8]=120

In [21]:
arr

array([ 10,  11,  12,  13,  14, 120, 120, 120,  18,  19])

In [24]:
arr_slice = arr[5:8]
arr_slice

array([200, 300, 400])

In [28]:
arr_slice[1]=99

In [29]:
arr_slice

array([200,  99, 400])

In [31]:
arr

array([ 10,  11,  12,  13,  14, 200,  99, 400,  18,  19])

In [ ]:
arr_slice

array([12345,    12,    20])

In [ ]:
# change values in arr_slice, the mutations are reflected in the original 
# array arr
arr_slice[0] = 12345

In [ ]:
arr

array([   10,    11,    12,    13,    14, 12345,    12,    20,    18,
          19])

In [ ]:
# using : only means all values
arr_slice[1:2] = 9999

In [205]:
arr_slice

array([11111,   200,    12])

In [203]:
arr[5]=11111

In [204]:
arr

array([   10,    11,    12,    13,    14, 11111,   200,    12,    18,
          19])

In [ ]:
# if you just assign a portion of an array to another array, the new array you just 
# created actually refers to the parent array in memory.
# That means, if you make any changes to the new array, it will reflect in the parent 
# array as well.

# So to avoid disturbing the parent array, you need to make a copy of it using copy(). 
# All numpy arrays come with the copy() method.

In [32]:
# If you want a copy of a slice of an ndarray instead of a view, you
# will need to explicitly copy the array — for example,
# arr[5:8].copy().
arr_slice1 = arr[5:8].copy()

In [33]:
arr

array([ 10,  11,  12,  13,  14, 200,  99, 400,  18,  19])

In [34]:
arr_slice1

array([200,  99, 400])

In [35]:
arr_slice1[1] = 10000

In [36]:
arr_slice1

array([  200, 10000,   400])

In [37]:
# the original array is not changed
arr

array([ 10,  11,  12,  13,  14, 200,  99, 400,  18,  19])

In [73]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
print(list2)
arr2 = np.array(list2, dtype='float')
arr2

[[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]]


array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [74]:
import numpy as np
list_arr = np.array([[1.2,2,3.8,4.5],[2.,4,9.2,5],[1,10,20,3],[100,210,210,23]], dtype = 'int')

In [75]:
list_arr

array([[  1,   2,   3,   4],
       [  2,   4,   9,   5],
       [  1,  10,  20,   3],
       [100, 210, 210,  23]])

In [77]:
list_arr.astype("str")

array([['1', '2', '3', '4'],
       ['2', '4', '9', '5'],
       ['1', '10', '20', '3'],
       ['100', '210', '210', '23']], dtype='<U11')

In [93]:
list_arr[:,2:3] 

array([[  3],
       [  9],
       [ 20],
       [210]])

In [34]:
list_arr[ 1:4, 1:3]

array([[  4,   9],
       [ 10,  20],
       [210, 210]])

In [35]:
print(list_arr[:,0])
print("_______________")
print(list_arr[1,0])
list_arr[:2, [0,2]]

[  1   2   1 100]
_______________
2


array([[1, 3],
       [2, 9]])

In [36]:
list_arr[1,0]=20

In [61]:
list_arr[:,:1], 

array([[1],
       [2],
       [1]])

In [66]:
list_arr[1:3, 1:3]

array([[ 4,  9],
       [10, 20]])

In [37]:
list_arr

array([[  1,   2,   3,   4],
       [ 20,   4,   9,   5],
       [  1,  10,  20,   3],
       [100, 210, 210,  23]])

In [143]:
list_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [15]:
list_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [14]:
ar2

array([  1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18])

In [46]:
import numpy as np
list_arr = np.arange(1,19)
list_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [47]:
list_arr.shape

(18,)

In [10]:
ar2 = list_arr.copy()

In [12]:
ar2 [1] = 100

In [42]:
len(list_arr)

18

In [48]:
list_arr1 = list_arr.reshape(6,3)
list_arr1, list_arr1.ndim, list_arr1.shape

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 2,
 (6, 3))

In [49]:
flat_arr = list_arr1.reshape(1,18)
flat_arr.ndim, flat_arr.shape, flat_arr

(2,
 (1, 18),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18]]))

In [50]:

a= flat_arr.flatten()

In [51]:
a, a.ndim, a.shape

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]),
 1,
 (18,))

In [52]:
a[1]=200

In [53]:
a

array([  1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18])

In [55]:
flat_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18]])

In [56]:
b= list_arr1.ravel()

In [58]:
b[3]=300

In [57]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [59]:
list_arr1

array([[  1,   2,   3],
       [300,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18]])

In [23]:
list_arr1[ 0:2, 0:2]

array([[  1,   2],
       [300,   5]])

In [25]:
arr2a = list_arr1[0:2,0:2]
arr2a


array([[  1,   2],
       [300,   5]])

In [28]:
arr2a

array([[ -1,   2],
       [300,   0]])

In [27]:
arr2a[0,0],  arr2a[1,1] = -1,0

In [31]:
list_arr1

array([[ -1,   2,   3],
       [300,   0,   6],
       [  7,   8,   9],
       [ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18]])

In [157]:
arr2a[:1,:1]

array([[-1]])

In [158]:
arr2a[:1, :1] = 50  # 100 will reflect in arr2
arr2a

array([[50,  1],
       [ 3,  0]])

In [ ]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [ ]:
arr2b

array([[101.,   2.],
       [  3.,   4.]])

In [ ]:
arr2

In [ ]:
# Indexing with slices
arr = np.arange(10)

In [ ]:
arr

In [ ]:
arr[1:6]

In [49]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [53]:
arr2d

array([[ 1,  2,  3],
       [60,  5,  6],
       [ 7,  8,  9]])

In [52]:
arr2d[1,0]=60

In [88]:
arr2d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [91]:
arr2d[0][1]

2

In [ ]:
# expression arr2d[:2] as “select the first two rows of arr2d.”
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# first 2 rows and all columns from 1st pos
arr2d[:2, 1:]


array([[2, 3],
       [5, 6]])

In [ ]:
arr2d

In [ ]:
# 1st row, all columns 0th and 1st
arr2d[1, :2]

In [ ]:
arr2d[:2, 2]

In [92]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
arr2d[:, 1]

array([2, 5, 8])

In [96]:
arr2d[:2,:1]

array([[1],
       [4]])

In [ ]:
arr2d[:2,:1] = 0

In [ ]:
arr2d

In [1]:
import numpy as np

In [17]:
from numpy.random import randint

In [62]:
randint(20)

7

In [65]:
arr=np.arange(10)

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr[[True,False,False,False,False,True,False,False,False,True]]

array([0, 5, 9])

In [62]:
# Boolean Indexing
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])
data = np.random.randint(30,100,size =(7, 4))

In [66]:
print("shape of names",names.shape, names.ndim)
print("shape of data",data.shape, data.ndim)

shape of names (7,) 1
shape of data (7, 4) 2


In [63]:
data

array([[33, 71, 86, 46],
       [93, 56, 94, 53],
       [67, 79, 83, 36],
       [51, 49, 42, 69],
       [62, 70, 96, 55],
       [84, 97, 55, 42],
       [61, 67, 44, 59]], dtype=int32)

In [64]:
# Suppose each name corresponds to a row in the data array and we wanted to 
# select all the rows with corresponding name 'Rajat'.
names == 'Rajat'

array([ True, False, False,  True, False, False, False])

In [65]:
data[names == 'Rajat']

array([[33, 71, 86, 46],
       [51, 49, 42, 69]], dtype=int32)

In [69]:
data[(names =='Rajat') | (names =='Bhanu')]

array([[33, 71, 86, 46],
       [51, 49, 42, 69],
       [62, 70, 96, 55]], dtype=int32)

In [38]:
data

array([[39, 70, 63, 35],
       [43, 82, 50, 69],
       [47, 48, 69, 71],
       [41, 76, 84, 94],
       [96, 32, 82, 85],
       [73, 76, 39, 33],
       [82, 82, 39, 30]])

In [78]:
data[ :,:  ]

array([[77, 56, 92, 66],
       [34, 30, 93, 75],
       [59, 60, 82, 57],
       [95, 67, 96, 32],
       [47, 44, 74, 80],
       [83, 61, 93, 30],
       [84, 32, 84, 40]], dtype=int32)

In [80]:
data[(2,6),3]

array([57, 40], dtype=int32)

In [45]:
data[(names == 'Rajat'),2]

array([88, 90], dtype=int32)

In [71]:
co= names == 'Rajat'

In [77]:
co

array([ True, False, False,  True, False, False, False])

In [74]:
data[co,:][:,1:3]

array([[71, 86],
       [49, 42]], dtype=int32)

In [86]:
data

array([[77, 56, 92, 66],
       [34, 30, 93, 75],
       [59, 60, 82, 57],
       [95, 67, 96, 32],
       [47, 44, 74, 80],
       [83, 61, 93, 30],
       [84, 32, 84, 40]], dtype=int32)

In [75]:
data[(names != 'Rajat'),:]

array([[93, 56, 94, 53],
       [67, 79, 83, 36],
       [62, 70, 96, 55],
       [84, 97, 55, 42],
       [61, 67, 44, 59]], dtype=int32)

In [79]:
~co

array([False,  True,  True, False,  True,  True,  True])

In [76]:
data[~co, :]

array([[93, 56, 94, 53],
       [67, 79, 83, 36],
       [62, 70, 96, 55],
       [84, 97, 55, 42],
       [61, 67, 44, 59]], dtype=int32)

In [ ]:
# The boolean array must be of the same length as the array axis it’s 
# indexing.

In [ ]:
# what happens if they are of different lengths
names = np.array(['Rajat', 'Maruthi', 'Rajat', 'Bhanu', 'Viswa' ])
data = np.random.randn(7, 4)

In [ ]:
a=np.array([['anad','sandeep'],['komal','d4']])
a

array([['anad', 'sandeep'],
       ['komal', 'd4']], dtype='<U7')

In [84]:
data[names == 'Rajat']

array([[66, 90, 56, 60],
       [97, 70, 72, 99]])

In [ ]:
names = np.array(['Rajat', 'Maruthi', 'Dinesh', 'Rajat', 'Bhanu', 'Viswa', 'Kamal'])
data = np.random.rand(7,4)

array([[0.24267668, 0.23552203, 0.34183445, 0.71250492],
       [0.70577654, 0.57598068, 0.69519404, 0.66891002],
       [0.19045848, 0.25865719, 0.22414758, 0.82526161],
       [0.63442703, 0.50927201, 0.8923701 , 0.17268299],
       [0.02299894, 0.38420888, 0.67698662, 0.47062065],
       [0.65579003, 0.35753625, 0.38685725, 0.99265001],
       [0.55472643, 0.78905374, 0.55657392, 0.94468923]])

In [ ]:
data[1,2]=2
data

array([[0.24267668, 0.23552203, 0.34183445, 0.71250492],
       [0.70577654, 0.57598068, 2.        , 2.        ],
       [0.19045848, 0.25865719, 0.22414758, 2.        ],
       [0.63442703, 0.50927201, 0.8923701 , 2.        ],
       [0.02299894, 0.38420888, 0.67698662, 0.47062065],
       [0.65579003, 0.35753625, 0.38685725, 0.99265001],
       [0.55472643, 0.78905374, 0.55657392, 0.94468923]])

In [169]:
data

array([[56, 71, 92, 72],
       [61, 98, 62, 78],
       [82, 99, 65, 94],
       [90, 92, 95, 93],
       [83, 95, 90, 75],
       [59, 87, 50, 68],
       [73, 53, 79, 66]])

In [56]:
data[names == 'Rajat']

array([[74, 87, 84, 74],
       [38, 65, 98, 44]])

In [58]:
names == 'Rajat'

array([ True, False, False,  True, False, False, False])

In [59]:
data[(0,3), 1]

array([87, 65])

In [205]:
data[names == 'Rajat']

array([[83, 69, 90, 62],
       [71, 43, 90, 77]])

In [49]:
data[names == 'Rajat', 1]

array([70, 76])

In [50]:
data[names == 'Rajat', 2:4]

array([[63, 35],
       [84, 94]])

In [92]:
data[names=='Rajat'][1,2]

np.int32(96)

In [95]:
data[names=='Rajat',:]

array([[77, 56, 92, 66],
       [95, 67, 96, 32]], dtype=int32)

In [80]:
data[names=='Rajat',:] [:,[1,2]]

array([[71, 86],
       [49, 42]], dtype=int32)

In [ ]:
# To select everything but 'Rajat', you can either use != or negate 
# the condition using ~

In [118]:
names != 'Rajat'

array([False,  True,  True, False,  True,  True,  True])

In [215]:
data[names != 'Rajat']

array([[63, 81, 41, 47],
       [81, 43, 98, 93],
       [66, 85, 86, 42],
       [58, 40, 41, 65],
       [79, 64, 41, 89]])

In [58]:
print("*******####")
data[~(names == 'Rajat')]

*******####


array([[71, 65, 48, 62],
       [58, 77, 68, 72],
       [59, 43, 48, 97],
       [48, 34, 36, 91],
       [94, 87, 69, 62]], dtype=int32)

In [59]:
cond= names == 'Rajat'
cond

array([ True, False, False,  True, False, False, False])

In [60]:
data[cond]

array([[97, 97, 88, 97],
       [90, 96, 90, 56]], dtype=int32)

In [61]:
data[~cond]

array([[71, 65, 48, 62],
       [58, 77, 68, 72],
       [59, 43, 48, 97],
       [48, 34, 36, 91],
       [94, 87, 69, 62]], dtype=int32)

In [ ]:
# Selecting two of the three names to combine multiple boolean conditions, 
# use boolean arithmetic operators like & (and) and | (or):

In [70]:
# The Python keywords and and or do not work with boolean arrays.
# Use & (and) and | (or) instead.
cond = (names == 'Rajat') |(names == 'Bhanu')

In [71]:
cond

array([ True, False, False,  True,  True, False, False])

In [73]:
data[~cond]

array([[82, 75, 57, 98],
       [66, 31, 33, 87],
       [79, 71, 57, 55],
       [40, 33, 57, 95]])

In [57]:
data

array([[39, 70, 63, 35],
       [43, 82, 50, 69],
       [47, 48, 69, 71],
       [41, 76, 84, 94],
       [96, 32, 82, 85],
       [73, 76, 39, 33],
       [82, 82, 39, 30]])

In [58]:
cond = data > 90

In [59]:
cond

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [60]:
data[cond]

array([94, 96])

In [61]:
data[cond] = 91

In [62]:
data

array([[39, 70, 63, 35],
       [43, 82, 50, 69],
       [47, 48, 69, 71],
       [41, 76, 84, 91],
       [91, 32, 82, 85],
       [73, 76, 39, 33],
       [82, 82, 39, 30]])

In [185]:
# change data for Rajat = 7
data[names != 'Rajat'] = 7

In [ ]:
name1="ABC"
name2= "XYZ"

if(name1 === name2):
    print("OK")
else:
    print("not ok")

In [ ]:
data

In [ ]:
# Transposing Arrays and Swapping Axes
# Transposing is a special form of reshaping that similarly returns a view on the underlying
# data without copying anything

In [100]:
a = np.array([(8,9,10),(11,12,13)])
print(a)
print("---------")
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
---------
[[ 8  9]
 [10 11]
 [12 13]]


In [62]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
arr12=arr.reshape(4,10)
arr12

ValueError: cannot reshape array of size 30 into shape (4,10)

In [47]:
arr12.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [107]:
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [117]:
arr12[::-1,]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [109]:
arr12[::-1,::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [ ]:
# Universal Functions: Fast Element-Wise Array Functions


In [81]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
f=np.sqrt(arr)

In [71]:
f

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [72]:
np.exp(f)

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692])

In [128]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
print(f)
np.floor(f), np.ceil(f)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


(array([0., 1., 1., 1., 2., 2., 2., 2., 2., 3.]),
 array([0., 1., 2., 2., 2., 3., 3., 3., 3., 3.]))

In [82]:
import numpy as np
new= np.arange(10)
new = new.astype(float)
new

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [223]:
type(np.nan)

float

In [86]:
new[3]=np.nan
new

array([ 0.,  1.,  2., nan,  4.,  5., nan,  7.,  8.,  9.])

In [87]:
np.isnan(new)

array([False, False, False,  True, False, False,  True, False, False,
       False])

In [88]:
sum(np.isnan(new))

np.int64(2)

In [90]:
str_arr = np.array(['a','b',np.nan, 'c'])

In [91]:
np.isnan(str_arr)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [82]:
new[np.isnan(new)]=100

In [83]:
new

array([  0.,   1.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.])

In [84]:
new[~np.isnan(new)]

array([  0.,   1.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.])

In [92]:
new[~np.isnan(new)]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [251]:
type(np.nan)

float

In [208]:
# useful in data anlytics
# is not a number
new[np.isnan(new)]

array([nan])

In [98]:
# binary functions
x = np.random.randint(5, size=10)
y = np.random.randint(8, size=10)
z = np.random.randint(8, size=10)

In [96]:
x

array([4, 1, 0, 3, 2, 3, 0], dtype=int32)

In [92]:
y

array([1, 7, 5, 2, 3, 2, 7, 4, 1, 5], dtype=int32)

In [93]:
z

array([5, 5, 1, 3, 6, 2, 3, 2, 5, 3], dtype=int32)

In [99]:
np.maximum(x, y)

array([7, 5, 2, 3, 5, 2, 6, 5, 7, 3], dtype=int32)

In [95]:
np.minimum(x, y,z)

array([0, 7, 3, 0, 3, 2, 1, 3, 0, 5], dtype=int32)

In [ ]:
# Array-Oriented Programming with Arrays
# NumPy arrays enables you to express many kinds of data processing tasks 
# as concise array expressions that might otherwise require writing loops

In [ ]:
# This practice of replacing explicit loops with array expressions 
# is commonly referred to as vectorization.

In [ ]:
# vectorized array operations will often be one or two (or more) orders
# of magnitude faster than their pure Python equivalents

In [ ]:
# to evaluate the function sqrt(x^2 + y^2) 
# across a regular grid of values.

In [263]:
points = np.arange(-5, 5, 0.5) # 1000 equally spaced points

In [264]:
points

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [91]:
x = np.arange(-5,5 ,1)
y = np.arange(10)

In [92]:
x

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [93]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.sqrt(np.add(x ** 2 , y ** 2))

array([5.        , 4.12310563, 3.60555128, 3.60555128, 4.12310563,
       5.        , 6.08276253, 7.28010989, 8.54400375, 9.8488578 ])

In [ ]:
# random number **********************************************

In [ ]:
# mean at 0 and standard deviation of 1
# This will return random floats in the half-open interval [0.0, 1.0) 
# following the “continuous uniform” distribution.
np.random.randn(5)

array([-0.9924059 , -0.46892582, -1.4275216 , -0.07190899, -1.12435409])

In [ ]:
np.random.random((2,2))

array([[0.96488998, 0.28109545],
       [0.36730077, 0.12298962]])

In [ ]:
# Generate A Random Number From The Normal Distribution
np.random.normal()

-3.377301897673844

In [ ]:
# Generate Four Random Numbers From The Normal Distribution
np.random.normal(size=4)

array([ 0.37459637, -0.95633897, -1.4055796 ,  0.73984779])

In [ ]:
# Random number from distribution with mean 15, variance 2
np.random.normal(15, 2)

13.74958447788593

In [95]:
# an array of 10 points randomly sampled from a normal distribution
# loc=mean, scale=std deviation
np.random.normal(loc=0.0, scale=1.0, size=10)

array([-0.62037639, -0.37694096,  1.92064025, -0.42296041,  0.57972771,
       -0.48914312,  1.61120537,  0.08602282,  0.91621237, -1.20176555])

In [96]:
# To return a 8 by 5 array of random numbers from the same distribution: 
np.random.normal(15, 2, size=(3, 4))

array([[12.22210666, 16.16590225, 16.89981162, 15.83296027],
       [13.10311138, 13.9940343 , 13.72930321, 15.72542067],
       [14.60268879, 15.2489122 , 14.54560561, 13.79163574]])

In [97]:
# A 5 by 3 array of random numbers from the standard normal distribution 
# with mean 1 and variance 1:

np.random.normal(size=(2, 4))

array([[-0.02477867, -0.99324955,  0.34408368, -0.76879137],
       [-0.20231287,  0.97090738,  0.28487766,  0.15959147]])

In [156]:
np.random.randint([1,10,20,30],[10,20,35,60], size =(3,4))

array([[ 9, 15, 21, 49],
       [ 4, 13, 22, 52],
       [ 6, 15, 22, 35]])

In [ ]:
# Generate Four Random Integers Between 1 and 100
np.random.randint(high =100, low =1, size =(3,4))

array([[88, 85, 93, 27],
       [49, 73, 84, 30],
       [60, 44, 57, 68]])

In [ ]:
# Randomly constructing 1D array
array = np.random.rand(5)
print("1D Array filled with random values : \n", array)

1D Array filled with random values : 
 [0.66875427 0.30678623 0.00891125 0.93981984 0.79342948]


In [ ]:
# Randomly constructing 1D array following Gaussian Distribution

# 1D Array
array = np.random.normal(0.0, 1.0, 5)
print("1D Array filled with random values "
      "as per gaussian distribution : \n", array)

# 3D array
array = np.random.normal(0.0, 1.0, (2, 3))
print("\n\n2D Array filled with random values "
      "as per gaussian distribution : \n", array)

In [ ]:
# Making random numbers predictable *******************

In [ ]:
# Set the state of the random number generator
np.random.seed(42)

In [ ]:
# One set of random numbers
first_random_arr = np.random.normal(size=(2, 2))
print(first_random_arr)

# Another set
second_random_arr = np.random.normal(size=(2, 2))
print(second_random_arr)

# Reset the state of the random number generator
np.random.seed(42)

# The same as "first_random_arr" above.
print(np.random.normal(size=(2, 2)))

# The same as "second_random_arr" above.
print(np.random.normal(size=(2, 2)))

In [123]:
arr1d_obj = np.array([[1, 'aaaaaaaaaaaaaaaa'],[1,2.6]])
arr1d_obj

array([['1', 'aaaaaaaaaaaaaaaa'],
       ['1', '2.6']], dtype='<U32')

In [124]:
# Create an object array to hold numbers as well as strings
arr1d_obj = np.array([[1, 'aaaaaaaaaaaaaaaa'],[1,2.6]], dtype = object)
arr1d_obj

array([[1, 'aaaaaaaaaaaaaaaa'],
       [1, 2.6]], dtype=object)

In [155]:
arr1d_obj.dtype

dtype('O')

In [157]:
type(arr1d_obj[0,0])

int

In [119]:
arr1d_obj.itemsize

8

In [122]:
type(arr1d_obj)

numpy.ndarray

In [125]:
# Convert an array back to a list
list_arr=arr1d_obj.tolist()
list_arr

[[1, 'aaaaaaaaaaaaaaaa'], [1, 2.6]]

In [159]:
a= np.random.randint(1,12,(3,4))
a

array([[ 4, 11,  6,  1],
       [ 8,  9,  2, 11],
       [ 7,  9, 11, 11]])

In [161]:
a=a.astype(float)

In [162]:
a[2,2] = np.nan

In [ ]:
a

array([[11.,  9.,  7.,  5.],
       [ 4.,  1.,  5.,  7.],
       [ 9., 11., nan,  9.]])

In [163]:
# Create a 2d array with 3 rows and 4 columns
import numpy as np
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [164]:
from numpy import random

In [165]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]

arr3 = np.array(random.randn(3,3))
arr3

array([[ 1.9728059 , -0.4977324 ,  1.84024179],
       [-0.52558666, -0.14036777, -0.58832172],
       [-1.55114796, -1.23620442,  0.17266479]])

In [166]:
arr3[1,1]=np.nan

In [167]:
arr3

array([[ 1.9728059 , -0.4977324 ,  1.84024179],
       [-0.52558666,         nan, -0.58832172],
       [-1.55114796, -1.23620442,  0.17266479]])

In [6]:
np.isnan(arr3)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [7]:
arr3[1,1]= -1

In [96]:
arr2=np.random.randint(10,50,size =(3,4))

In [97]:
arr2 = arr2.astype(float)

In [98]:
arr2[::-1,]

array([[27., 37., 20., 26.],
       [41., 35., 38., 13.],
       [38., 14., 14., 35.]])

In [128]:
# Reverse the row and column positions

arr2[::-1, ::-1]

array([[29., 17., 41., 46.],
       [11., 20., 45., 42.],
       [22., 10., 36., 27.]])

In [99]:
# represent missing values and infinite?
# Missing values can be represented using np.nan object, while np.inf represents infinite. 
# Let’s place some in arr2d.

# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[38., 14., 14., 35.],
       [41., nan, inf, 13.],
       [27., 37., 20., 26.]])

In [100]:
cond= np.isnan(arr2)|np.isinf(arr2)
cond

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False, False, False]])

In [102]:
arr2[cond]=-800
arr2

array([[  38.,   14.,   14.,   35.],
       [  41., -800., -800.,   13.],
       [  27.,   37.,   20.,   26.]])

In [228]:
type(np.nan)

float

In [172]:
arr2

array([[   1.,    2.,    3.,    4.],
       [   3., -800., -800.,    6.],
       [   5.,    6.,    7.,    8.]])

In [226]:
arr2.astype("float")

array([[ 1.,  2.,  3.,  4.],
       [ 3., -2., -2.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [232]:
arr2.dtype

dtype('float64')

In [224]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -2., -2.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [ ]:
# Replace nan and inf with -1. 
missing_bool = np.isnan(arr2) | np.isinf(arr2)
print(missing_bool)

arr2[missing_bool] = -1  
#missing_bool = -1  
missing_bool
arr2

[[False False False False]
 [False  True  True False]
 [False False False False]]


array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [103]:
# compute mean, min, max on the ndarray
# mean, max and min
print("Mean value is: ", arr2.mean())
print("Max value is: ", arr2.max())
print("Min value is: ", arr2.min())

Mean value is:  -111.25
Max value is:  41.0
Min value is:  -800.0


In [122]:
arr2

array([[  25.,   41.,   31.,   14.],
       [  20., -800., -800.,   23.],
       [  48.,   15.,   32.,   32.]])

In [123]:
np.amin(arr2,axis=0)

array([  20., -800., -800.,   14.])

In [124]:
np.amin(arr2, axis = 1)

array([  14., -800.,   15.])

In [ ]:
# compute the minimum values row wise or column wise, use the np.amin 
 np.amin(arr2, axis=0)
print("Column wise minimum : ", np.amin(arr2, axis=0))
print("Row wise minimum    : ", np.amin(arr2, axis=1))

Column wise minimum :  [ 1. -1. -1.  4.]
Row wise minimum    :  [ 1. -1.  5.]


In [125]:
import numpy as np
#A better approach is to move the one-dimensional innermost loop into your code, external to the iterator. This way, NumPy’s vectorized operations can be used on larger chunks of the elements being visited.# Row wise and column wise min
a = np.arange(6).reshape(2,3)
print(a)
print("########## after nditer")



[[0 1 2]
 [3 4 5]]
########## after nditer


In [102]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [100]:
for x in np.nditer(a,order = "K" , flags=['external_loop']):
    print(x)
 
type(x)


[0 1 2 3 4 5]


numpy.ndarray

In [ ]:
for x in np.nditer(a,order = "F" , flags=['external_loop']):
    print(x)

[0 3]
[1 4]
[2 5]


In [ ]:
a = np.arange(6).reshape(2,3)
it = np.nditer(a, flags=['f_index'])
while not it.finished:
    print("%d <%d>" % (it[0], it.index), end=' ')
    it.iternext()

0 <0> 1 <2> 2 <4> 3 <1> 4 <3> 5 <5> 

In [ ]:
it = np.nditer(a, flags=['multi_index'])
while not it.finished:
    print("%d <%s>" % (it[0], it.multi_index), end=' ')
    it.iternext()

0 <(0, 0)> 1 <(0, 1)> 2 <(0, 2)> 3 <(1, 0)> 4 <(1, 1)> 5 <(1, 2)> 

In [ ]:
it = np.nditer(a, flags=['multi_index'], op_flags=['writeonly'])
with it:
    while not it.finished:
        it[0] = it.multi_index[1] - it.multi_index[0]
        it.iternext()

In [ ]:
a

array([[ 0,  1,  2],
       [-1,  0,  1]])

In [ ]:
# Reshaping and Flattening Multidimensional arrays
# Reshaping is changing the arrangement of items so that shape of the array changes 
# while maintaining the same number of dimensions.

# Flattening, however, will convert a multi-dimensional array to a flat 1d array. 
# And not any other shape.

# First, let’s reshape the arr2 array from 3×4 to 4×3 shape.

In [ ]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(4, 3)
arr2.reshape(6,2)

array([[1., 2.],
       [3., 4.],
       [3., 4.],
       [5., 6.],
       [5., 6.],
       [7., 8.]])

In [ ]:
# What is the difference between flatten() and ravel()?
# There are 2 popular ways to implement flattening. That is using the flatten() method 
# and the other using the ravel() method.

# The difference between ravel and flatten is, the new array created using ravel is 
# actually a reference to the parent array. 
# So, any changes to the new array will affect the parent as well. 
# But is memory efficient since it does not create a copy.

In [109]:
arr2

array([[  38.,   14.,   14.,   35.],
       [  41., -800., -800.,   13.],
       [  27.,   37.,   20.,   26.]])

In [106]:
# Flatten it to a 1d array
flat = arr2.flatten()

In [110]:
flat.shape , flat.ndim

((12,), 1)

In [111]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 105  # changing b1 does not affect arr2
arr2

array([[  38.,   14.,   14.,   35.],
       [  41., -800., -800.,   13.],
       [  27.,   37.,   20.,   26.]])

In [112]:
b1

array([ 105.,   14.,   14.,   35.,   41., -800., -800.,   13.,   27.,
         37.,   20.,   26.])

In [178]:
arr2

array([[   1.,    2.,    3.,    4.],
       [   3., -800., -800.,    6.],
       [   5.,    6.,    7.,    8.]])

In [ ]:
arr2.ravel() 

array([ 1.,  2.,  3.,  4.,  3., -1., -1.,  6.,  5.,  6.,  7.,  8.])

In [113]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
arr2


array([[ 101.,   14.,   14.,   35.],
       [  41., -800., -800.,   13.],
       [  27.,   37.,   20.,   26.]])

In [114]:
b2

array([ 101.,   14.,   14.,   35.,   41., -800., -800.,   13.,   27.,
         37.,   20.,   26.])

In [31]:
id(arr2), id(b2), id(b1)

(2041139809056, 2041174159648, 2041174425472)

In [35]:
arr2[1,1]=20

In [37]:
id(b2[5]), id(arr2[1,1])

(2041174458608, 2041174458608)

In [ ]:
# create sequences, repetitions 
# Lower limit is 0 be default
print(np.arange(5))  

In [ ]:
# 0 to 9
print(np.arange(0, 10))  

In [ ]:
# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

[0 2 4 6 8]


In [ ]:
# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


In [82]:
# create repeating sequences?
# np.tile will repeat a whole list or array n times. 
# Whereas, np.repeat repeats each item n times.

a = [1,2,3] 

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 4))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 4))

Tile:    [1 2 3 1 2 3 1 2 3 1 2 3]
Repeat:  [1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
# Arrays support vectorised operations, while lists don’t.
# Once an array is created, you cannot change its size. You will have to create a new array 
# or overwrite the existing one.
# Every array has one and only one dtype. All items in it should be of that dtype.
# An equivalent numpy array occupies much less space than a python list of lists.

In [2]:
a= [1,2,3,4,5]
b=[10,20,30,40,50]
list(map(lambda x: x+y, a))

NameError: name 'y' is not defined

In [5]:
def input_dic(**ar): 
    print(**ar)

In [6]:
input_dic(a=10,b=20)

TypeError: 'a' is an invalid keyword argument for print()

In [7]:
def new_add(*s):
    print(s)
    total =0
    for i in s:
        total = total +i
    return total

In [8]:
new_add([1,2,3])

([1, 2, 3],)


TypeError: unsupported operand type(s) for +: 'int' and 'list'