In [4]:
import time
import random
from math import *
import operator
import pandas as pd
import numpy as np

# import plotting libraries
import matplotlib
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline

import seaborn as sns
sns.set(style="white", color_codes=True)
sns.set(font_scale=1.5)

# import the ML algorithm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from statsmodels.tools.eval_measures import rmse
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree

# pre-processing
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import Normalizer
##from sklearn.preprocessing.data import QuantileTransformer
#from sklearn.preprocessing import Imputer
from sklearn.decomposition import PCA


# import libraries for model validation
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import KFold
##from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut

# import libraries for metrics and reporting
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn import metrics
from sklearn.metrics import classification_report

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# DecisionTreeClassifier is a class capable of performing multi-class classification on a dataset.
# As with other classifiers, DecisionTreeClassifier takes as input two arrays:
#    - an array X, sparse or dense, of size [n_samples, n_features] holding the training samples,
#    - an array y of integer values, size [n_samples], holding the class labels for the
#      training samples:

In [ ]:
X = [[0, 0],[2,2], [3,3], [1, 1]]

y = [0,2, 3, 1]
print(X)
y

[[0, 0], [2, 2], [3, 3], [1, 1]]


[0, 2, 3, 1]

In [ ]:
clf = tree.DecisionTreeClassifier()

clf = clf.fit(X, y)

In [ ]:
# After being fitted, the model can then be used to predict the class of samples:
clf.predict([[2., 1.]])

array([1])

In [ ]:
# Alternatively, the probability of each class can be predicted, which is the fraction of
# training samples of the same class in a leaf
clf.predict_proba([[0, 3.]])

array([[1., 0., 0., 0.]])

In [3]:
location = r"/content/drive/MyDrive/PIBM/datasets/iris.csv"

In [5]:
# load the training data from breast cancer data set
df_iris = pd.read_csv(location)
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
# copy the predictor variables into X and responses in y
X = df_iris[['sepal_length','sepal_width', 'petal_length', 'petal_width']]
y = df_iris['class']

In [7]:
# split the data into training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=24)

In [ ]:
X_train.shape

(105, 4)

In [12]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: object

In [8]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
clf

DecisionTreeClassifier(criterion='entropy')

In [9]:
!pip install graphviz

In [ ]:
# Install windows package from:
# !pip install graphviz
# https://graphviz.gitlab.io/_pages/Download/Download_windows.html
# Install python graphviz package (pip install graphviz)
## conda install python-graphviz
# Add ...\Graphviz2.38\bin to User path
# Add ...\Graphviz2.38\bin\dot.exe to System Path

In [ ]:
df_iris.drop('class' , 1).columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [ ]:
!pip install graphviz

In [13]:
import graphviz
from sklearn.tree import export_graphviz
# dot_data = tree.export_graphviz(clf, out_file=None)
# graph = graphviz.Source(dot_data)
# graph.render("C:\\Users\\user\\Desktop\\iris")

In [14]:
dot_data = export_graphviz(clf,
                         out_file=None,
                         feature_names=df_iris.drop('class' , 1).columns,
                         class_names=df_iris["class"].unique(),
                           #class_names=y.unique(),
                          filled=True,
                          rounded=True,
                          special_characters= False)

graph = graphviz.Source(dot_data)

#graph.render(r"E:\Python\Machine Learning\DT_graph_iris")
graph

KeyError: "['class'] not found in axis"

In [ ]:
# After being fitted, the model can then be used to predict the class of samples:

y_pred = clf.predict(X_test)

In [ ]:
# print the confusion metrics
metrics.confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 0, 11,  1],
       [ 0,  1, 17]], dtype=int64)

In [ ]:
# accuracy score
metrics.accuracy_score(y_test, y_pred)

0.9555555555555556

In [ ]:
# classification report
print(classification_report(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.92      0.92      0.92        12
 Iris-virginica       0.94      0.94      0.94        18

       accuracy                           0.96        45
      macro avg       0.95      0.95      0.95        45
   weighted avg       0.96      0.96      0.96        45

